### ISSUE TITLE
Some ply functions can't work?

### ISSUE THREAD

**Issue by tiger20081015** [iovisor/ply#54] opened 2020-06-18 02:49 UTC
hi, I enabled ply in our embedded target board, and can successfully run commands like:

```
 ply 'tracepoint:irq/irq_handler_entry { @[data->irq] = count(); }'
 ply 'kretprobe:vfs_read { @[pid] = quantize(retval); }'
 ply 'tracepoint:sched/sched_switch { @[kstack] = count();}'
```

But when I want to print syscall's argument, it can't be printed out. For example:
     `  ply 'kprobe:do_sys_open { printf("opened:%s\n", str(arg1));}'_`
then I opened a file. But only prints out:
     `   opened`
The str(arg1) seems empty...

Also met below errors when I tried to run commands in https://www.slideshare.net/brendangregg/linux-4x-tracing-performance-analysis-with-bccbpf

```
_sh-4.4# ply 'kprobe:do_sys_open { printf("%s %ld\n", comm, nsecs()); }'
<input>:1:46-51: error: type of symbol 'nsecs' is unknown
<input>:1:21-54: error: type of symbol ':struct' is unknown
<input>:1:21-54: error: type of symbol ':struct' is unknown

```
```
sh-4.4# ply 'kretprobe:vfs_read { @[func()] = quantize(retval); }'                                                                                                                                          
<input>:1:21-22: error: type of symbol '@' is unknown
<input>:1:23-27: error: type of symbol 'func' is unknown
<input>:1:22-30: error: type of symbol ':struct' is unknown
```

Is it because func() and nsecs() are not available in current ply? Are there any alternative functions?Thanks.

**Comment by wkz** [comment] 2020-06-22 07:38
> But when I want to print syscall's argument, it can't be printed out. For example:

I'm not able to reproduce it on neither x86_64 nor aarch64 which are the systems easily available to me right now. Which arch are you on?

> Is it because func() and nsecs() are not available in current ply? Are there any alternative functions?Thanks.

Yes, you're looking for `caller` and `time`/`walltime`. They are described in the manual:

https://wkz.github.io/ply/ply.1.html

**Comment by tiger20081015** [comment] 2020-06-23 01:04
> > But when I want to print syscall's argument, it can't be printed out. For example:
> 
> I'm not able to reproduce it on neither x86_64 nor aarch64 which are the systems easily available to me right now. Which arch are you on?
I reproduced this issue on arm64, coretex-a76.  Is it possible that some kernel configurations are sett incorrectly?

**Comment by wkz** [comment] 2020-06-29 16:24
It's possible, but I can't think of anything that would allow the probes to be inserted but stop the data from being received :thinking:

**Comment by tiger20081015** [comment] 2020-07-14 09:09
@wkz , the issue seems related to str() function. I used "ply 'kprobe:do_sys_open { printf("fswu %s %d\n", comm, arg2); }" and the arg2 can be printed out.  Is it ok to use str() to convert to a string?

**Comment by wkz** [comment] 2020-07-18 19:48
Yes that should work fine.

I get the expected output if I copy your command verbatim to my QEMU instance. Can you run your kernel and rootfs under QEMU? If so, do you see the same lack of output there?

```
/ # ply 'kprobe:do_sys_open { printf("opened:%s\n", str(arg1));}' &
/ # ply: active

opened:/etc/passwd
/ # uname -a
opened:/.ash_history
opened:/etc/ld.so.cache
opened:/lib64/tls/aarch64/libm.so.6
opened:/lib64/tls/libm.so.6
opened:/lib64/aarch64/libm.so.6
opened:/lib64/libm.so.6
opened:/usr/lib64/tls/aarch64/libm.so.6
opened:/usr/lib64/tls/libm.so.6
opened:/usr/lib64/aarch64/libm.so.6
opened:/usr/lib64/libm.so.6
opened:/lib64/libresolv.so.2
opened:/lib64/libc.so.6
Linux (none) 5.5.8 #1 SMP PREEMPT Sun Mar 8 22:58:48 CET 2020 aarch64 GNU/Linux
opened:/etc/passwd
/ # 
```

**Comment by wkz** [comment] 2020-09-08 12:24
No feedback in well over a month; closing.

**Closed by wkz** 2020-09-08 12:24 UTC
